/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7a528142-5343-4210-bcea-a2fdf4f8cbe0

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 45151b71-62f8-4ff4-8abc-91ebcb440971

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

inductive BSeq : Type
  | nil : BSeq
  | cons : BSeq → BSeq → BSeq
deriving DecidableEq, Repr

def BSeq.append : BSeq → BSeq → BSeq
  | BSeq.nil,      t => t
  | BSeq.cons x y, t => BSeq.cons x (BSeq.append y t)

instance : HAdd BSeq BSeq BSeq := ⟨BSeq.append⟩

/-- semilength / number of edges `|x|`. -/
def BSeq.semilen : BSeq → Nat
  | BSeq.nil      => 0
  | BSeq.cons x y => BSeq.semilen x + BSeq.semilen y + 1

@[simp] theorem BSeq.semilen_nil : BSeq.semilen BSeq.nil = 0 := rfl
@[simp] theorem BSeq.semilen_cons (x y : BSeq) :
    BSeq.semilen (BSeq.cons x y) = BSeq.semilen x + BSeq.semilen y + 1 := rfl

def leavesPairOfSeq : BSeq → Nat × Nat
  | BSeq.nil => (1, 0)
  | BSeq.cons x y =>
      let px := leavesPairOfSeq x
      let py := leavesPairOfSeq y
      (px.1 + py.2, px.1 + py.2)

def treeLeavesOfSeq (s : BSeq) : Nat := (leavesPairOfSeq s).1
def forestLeavesOfSeq (s : BSeq) : Nat := (leavesPairOfSeq s).2

@[simp] theorem treeLeaves_nil : treeLeavesOfSeq BSeq.nil = 1 := by rfl
@[simp] theorem forestLeaves_nil : forestLeavesOfSeq BSeq.nil = 0 := by rfl

/-- Useful rewrite for cons. -/
@[simp] theorem treeLeaves_cons (x y : BSeq) :
    treeLeavesOfSeq (BSeq.cons x y) = treeLeavesOfSeq x + forestLeavesOfSeq y := by
  simp [treeLeavesOfSeq, forestLeavesOfSeq, leavesPairOfSeq, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm]

@[simp] theorem forestLeaves_cons (x y : BSeq) :
    forestLeavesOfSeq (BSeq.cons x y) = treeLeavesOfSeq (BSeq.cons x y) := by
  simp [treeLeavesOfSeq, forestLeavesOfSeq, leavesPairOfSeq]

class LozanoContext where
  R : BSeq → Finset BSeq
  S : BSeq → Finset BSeq
  R_card : ∀ x : BSeq, (R x).card = BSeq.semilen x + 1
  lemma5 : ∀ x y : BSeq, (S (x + y) : Set BSeq) ⊆ (S x ∪ S y : Finset BSeq)
  S_cons_def : ∀ x y : BSeq, S (BSeq.cons x y) = R x ∪ S (x + y)
  S_cons_card_le : ∀ x y : BSeq, (S (BSeq.cons x y)).card ≤ (R x).card + (S x).card + (S y).card
  treeLeaves_pos : ∀ x : BSeq, 1 ≤ treeLeavesOfSeq x

export LozanoContext (R S R_card lemma5 S_cons_def S_cons_card_le treeLeaves_pos)

class LozanoContextFull extends LozanoContext where
  R_nil : R BSeq.nil = {BSeq.nil}
  R_cons : ∀ x y, R (BSeq.cons x y) = insert (BSeq.cons x y) (R (x + y))
  S_nil : S BSeq.nil = {BSeq.nil}

export LozanoContextFull (R_nil R_cons S_nil)

theorem S_subset_R_of_treeLeaves_eq_one [LozanoContextFull] (x : BSeq) (h : treeLeavesOfSeq x = 1) :
    S x ⊆ R x := by
      -- By induction on the structure of x, we can show that S x is a subset of R x.
      induction' x with x ih;
      · -- By definition of $S$ and $R$, we know that $S BSeq.nil = {BSeq.nil}$ and $R BSeq.nil = {BSeq.nil}$.
        have h_S_nil : (‹LozanoContextFull›).S BSeq.nil = {BSeq.nil} := by
          exact?
        have h_R_nil : (‹LozanoContextFull›).R BSeq.nil = {BSeq.nil} := by
          exact?;
        aesop;
      · have := ‹LozanoContextFull›.treeLeaves_pos x; have := ‹LozanoContextFull›.treeLeaves_pos ih; simp_all +arith +decide;
        -- Since $forestLeavesOfSeq ih + treeLeavesOfSeq x = 1$ and both $forestLeavesOfSeq ih$ and $treeLeavesOfSeq x$ are at least 1, this leads to a contradiction.
        have h_contra : forestLeavesOfSeq ih = 0 ∧ treeLeavesOfSeq x = 1 := by
          omega;
        -- Since `forestLeavesOfSeq ih = 0`, we have that `ih` must be the empty sequence.
        have h_ih_empty : ih = BSeq.nil := by
          contrapose! h_contra; induction ih <;> aesop;
        have := ‹LozanoContextFull›.S_cons_def x BSeq.nil; simp_all +decide [ Finset.subset_iff ] ;
        have := ‹LozanoContextFull›.R_cons x BSeq.nil; simp_all +decide [ Finset.subset_iff ] ;
        -- Since $x$ is a binary sequence, adding $BSeq.nil$ to it does not change it. Therefore, $x + BSeq.nil = x$.
        have h_add_nil : x + BSeq.nil = x := by
          have h_add_nil : ∀ x : BSeq, x + BSeq.nil = x := by
            -- We can prove this by induction on the structure of `x`.
            intro x
            induction' x with x ih;
            · rfl;
            · -- By definition of addition for BSeq, adding BSeq.nil to any sequence x results in x itself.
              have h_add_nil : ∀ x : BSeq, x + BSeq.nil = x := by
                -- We can prove this by induction on the structure of `x` using the definition of addition for BSeq.
                intro x
                induction' x with x ih;
                · rfl;
                · -- By definition of addition for BSeq, adding BSeq.nil to a cons sequence results in the same cons sequence.
                  have h_add_nil : ∀ x y : BSeq, x.cons y + BSeq.nil = x.cons (y + BSeq.nil) := by
                    exact?;
                  rw [ h_add_nil, ‹ih + BSeq.nil = ih› ];
              exact h_add_nil _;
          apply h_add_nil;
        aesop

theorem semilen_append (x y : BSeq) :
    BSeq.semilen (x + y) = BSeq.semilen x + BSeq.semilen y := by
      -- We can prove this by induction on $x$.
      induction' x with x ih;
      · -- By definition of addition for BSeqs, we have BSeq.nil + y = y.
        have h_add_nil : BSeq.nil + y = y := by
          exact?;
        rw [ h_add_nil, BSeq.semilen_nil, zero_add ];
      · -- By definition of semilen, we have:
        have h_semilen_cons : ∀ x y : BSeq, (x.cons y).semilen = x.semilen + y.semilen + 1 := by
          exact?;
        convert h_semilen_cons x ( ih + y ) using 1;
        linarith [ h_semilen_cons x ih ]

theorem forestLeaves_add (x y : BSeq) :
    forestLeavesOfSeq (x + y) = forestLeavesOfSeq x + forestLeavesOfSeq y := by
      -- By definition of forestLeavesOfSeq, we have that forestLeavesOfSeq (x + y) = forestLeavesOfSeq x + forestLeavesOfSeq y.
      induction' x with x ih generalizing y;
      · aesop;
      · -- By definition of forestLeavesOfSeq, we have forestLeavesOfSeq (x.cons ih + y) = forestLeavesOfSeq (x.cons (ih + y)).
        have h_def : forestLeavesOfSeq (x.cons ih + y) = forestLeavesOfSeq (x.cons (ih + y)) := by
          congr;
        simp_all +decide [ leavesPairOfSeq ] ; ring!;

theorem treeLeaves_eq_forestLeaves_of_ne_nil (x : BSeq) (h : x ≠ BSeq.nil) :
    treeLeavesOfSeq x = forestLeavesOfSeq x := by
  cases x
  · contradiction
  · simp [treeLeaves_cons, forestLeaves_cons]

theorem lemma7_algebra (a b tu tv : Nat) (htu : 1 ≤ tu) (htv : 1 ≤ tv) :
    a + a * tu + b * tv + 3 ≤ (a + b + 1) * (tu + tv) + 1 := by
      nlinarith

theorem R_mem_semilen_le [LozanoContextFull] (x : BSeq) :
    ∀ z ∈ R x, BSeq.semilen z ≤ BSeq.semilen x := by
  induction x using BSeq.rec with
  | nil =>
    rw [LozanoContextFull.R_nil]
    simp
  | cons u v IHu IHv =>
    -- This structural induction is not enough because R (cons u v) depends on R (u + v).
    -- We need strong induction on semilen or a measure.
    intro z hz;
    -- By definition of $R$, we know that $R (u.cons v) = insert (u.cons v) (R (u + v))$.
    have hR_cons : (‹LozanoContextFull›.R (u.cons v)) = insert (u.cons v) (‹LozanoContextFull›.R (u + v)) := by
      exact?;
    -- By definition of $R$, we know that $R (u + v)$ contains sequences whose semilen is at most semilen (u + v).
    have hR_uv : ∀ z ∈ (‹LozanoContextFull›.R (u + v)), z.semilen ≤ (u + v).semilen := by
      -- By induction on the length of $u + v$, we can show that $R (u + v)$ is a subset of sequences with semilen at most $(u + v).semilen$.
      have h_ind : ∀ n : ℕ, ∀ x : BSeq, x.semilen = n → ∀ z ∈ (‹LozanoContextFull›.R x), z.semilen ≤ x.semilen := by
        intro n x hx z hz; induction' n using Nat.strong_induction_on with n ih generalizing x z; rcases x with ( _ | ⟨ u, v ⟩ ) <;> simp_all +decide ;
        · have := ‹LozanoContextFull›.R_nil; aesop;
        · -- By definition of $R$, we know that $R (u.cons v) = insert (u.cons v) (R (u + v))$ and $R (u + v)$ is a subset of sequences with semilen at most $(u + v).semilen$.
          have hR_uv : ∀ z ∈ (‹LozanoContextFull›.R (u + v)), z.semilen ≤ (u + v).semilen := by
            apply ih (BSeq.semilen (u + v)) (by
            rw [ ← hx ];
            rw [ semilen_append ] ; simp +arith +decide) (u + v) (by
            rfl);
          simp_all +decide [ LozanoContextFull.R_cons ];
          rcases hz with ( rfl | hz ) <;> [ exact hx ▸ by simp +arith +decide; ; exact le_trans ( hR_uv _ hz ) ( by simp +arith +decide [ ← hx, semilen_append ] ) ] ;
      exact h_ind _ _ rfl;
    -- By definition of $R$, we know that $z$ is either $u.cons v$ or in $R (u + v)$.
    cases' Finset.mem_insert.mp (hR_cons ▸ hz) with hz_cons hz_Ruv;
    · rw [hz_cons];
    · refine le_trans ( hR_uv z hz_Ruv ) ?_;
      rw [ semilen_append ] ; simp +arith +decide [ BSeq.semilen_cons ] ;

theorem S_mem_semilen_lt [LozanoContextFull] (x : BSeq) (hx : x ≠ BSeq.nil) :
    ∀ z ∈ S x, BSeq.semilen z < BSeq.semilen x := by
  induction x using BSeq.rec with
  | nil => contradiction
  | cons u v IHu IHv =>
    intro z hz
    rw [LozanoContext.S_cons_def] at hz
    rcases Finset.mem_union.mp hz with h_Ru | h_Suv
    · -- z ∈ R u
      have : BSeq.semilen z ≤ BSeq.semilen u := R_mem_semilen_le u z h_Ru
      calc BSeq.semilen z ≤ BSeq.semilen u := this
        _ < BSeq.semilen u + BSeq.semilen v + 1 := by linarith
        _ = BSeq.semilen (BSeq.cons u v) := by simp
    · -- z ∈ S (u + v)
      -- We need |z| < |cons u v|.
      -- If u+v != nil, then |z| < |u+v| = |u| + |v| < |cons u v|.
      -- If u+v = nil, S(u+v) = {nil}, z=nil, 0 < |cons u v|.
      by_cases huv : u + v = BSeq.nil
      · rw [huv, LozanoContextFull.S_nil] at h_Suv
        have : z = BSeq.nil := Finset.mem_singleton.mp h_Suv
        rw [this, BSeq.semilen_nil, BSeq.semilen_cons]
        linarith
      · have : BSeq.semilen z < BSeq.semilen (u + v) := by
          -- We need the IH for (u+v). But structural induction on x doesn't give IH for (u+v).
          -- We need strong induction on semilen.
          -- Or we can prove this lemma by strong induction on semilen x.
          -- By the definition of $S$, if $z \in S (u + v)$, then $z \in R (u + v)$ or $z \in S (u + v)$.
          apply (‹LozanoContextFull›.lemma5 u v) |> fun h => by
            cases eq_or_ne u BSeq.nil <;> cases eq_or_ne v BSeq.nil <;> simp_all +decide [ Set.subset_def ];
            · exact?;
            · cases h z h_Suv <;> simp_all +decide [ LozanoContextFull.S_nil ];
              · rw [ semilen_append ] ; aesop;
              · cases u <;> simp_all +decide [ BSeq.semilen ];
                exact Nat.succ_pos _;
            · cases h z h_Suv <;> simp_all +decide [ semilen_append ];
              · exact lt_add_of_lt_of_nonneg ( IHu _ ‹_› ) ( Nat.zero_le _ );
              · exact lt_of_lt_of_le ( IHv _ ‹_› ) ( Nat.le_add_left _ _ )
        rw [semilen_append] at this
        rw [BSeq.semilen_cons]
        linarith

def R_comp : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => insert (BSeq.cons x y) (R_comp (x + y))
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try rw [semilen_append]
    try rw [BSeq.semilen_cons]
    omega

def S_comp : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => R_comp x ∪ S_comp (x + y)
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try rw [semilen_append]
    try rw [BSeq.semilen_cons]
    omega

def check_lemma7 (x : BSeq) : Bool :=
  (S_comp x).card ≤ BSeq.semilen x * treeLeavesOfSeq x + 1

#eval! check_lemma7 BSeq.nil
#eval! check_lemma7 (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_lemma7 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_lemma7 (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_lemma7 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def R_comp_v4 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => insert (BSeq.cons x y) (R_comp_v4 (x + y))
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try simp [semilen_append, BSeq.semilen_cons]
    try omega

def S_comp_v4 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => R_comp_v4 x ∪ S_comp_v4 (x + y)
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try simp [semilen_append, BSeq.semilen_cons]
    try omega

def check_lemma7_v4 (x : BSeq) : Bool :=
  (S_comp_v4 x).card ≤ BSeq.semilen x * treeLeavesOfSeq x + 1

#eval! check_lemma7_v4 BSeq.nil
#eval! check_lemma7_v4 (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_lemma7_v4 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_lemma7_v4 (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_lemma7_v4 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def R_comp_v8 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => insert (BSeq.cons x y) (R_comp_v8 (x + y))
termination_by x => BSeq.semilen x
decreasing_by
  simp_wf
  try simp [semilen_append, BSeq.semilen_cons]
  try omega

def S_comp_v8 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => R_comp_v8 x ∪ S_comp_v8 (x + y)
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try simp [semilen_append, BSeq.semilen_cons]
    try omega

def check_lemma7_v8 (x : BSeq) : Bool :=
  (S_comp_v8 x).card ≤ BSeq.semilen x * treeLeavesOfSeq x + 1

#eval! check_lemma7_v8 BSeq.nil
#eval! check_lemma7_v8 (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_lemma7_v8 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_lemma7_v8 (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_lemma7_v8 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def R_comp_v10 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => insert (BSeq.cons x y) (R_comp_v10 (x + y))
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    simp [semilen_append, BSeq.semilen_cons]
    try omega

def S_comp_v10 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => R_comp_v10 x ∪ S_comp_v10 (x + y)
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    simp [semilen_append, BSeq.semilen_cons]
    try omega

def check_lemma7_v10 (x : BSeq) : Bool :=
  (S_comp_v10 x).card ≤ BSeq.semilen x * treeLeavesOfSeq x + 1

#eval! check_lemma7_v10 BSeq.nil
#eval! check_lemma7_v10 (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_lemma7_v10 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_lemma7_v10 (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_lemma7_v10 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def R_comp_v11 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => insert (BSeq.cons x y) (R_comp_v11 (x + y))
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try simp [semilen_append, BSeq.semilen_cons]
    try omega

def S_comp_v11 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => R_comp_v11 x ∪ S_comp_v11 (x + y)
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try simp [semilen_append, BSeq.semilen_cons]
    try omega

def check_lemma7_v11 (x : BSeq) : Bool :=
  (S_comp_v11 x).card ≤ BSeq.semilen x * treeLeavesOfSeq x + 1

#eval! check_lemma7_v11 BSeq.nil
#eval! check_lemma7_v11 (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_lemma7_v11 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_lemma7_v11 (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_lemma7_v11 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def R_comp_v13 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => insert (BSeq.cons x y) (R_comp_v13 (x + y))
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    simp [semilen_append, BSeq.semilen_cons]
    try omega

def S_comp_v13 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => R_comp_v13 x ∪ S_comp_v13 (x + y)
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    simp [semilen_append, BSeq.semilen_cons]
    try omega

def check_lemma7_v13 (x : BSeq) : Bool :=
  (S_comp_v13 x).card ≤ BSeq.semilen x * treeLeavesOfSeq x + 1

#eval! check_lemma7_v13 BSeq.nil
#eval! check_lemma7_v13 (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_lemma7_v13 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_lemma7_v13 (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_lemma7_v13 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def R_comp_v14 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => insert (BSeq.cons x y) (R_comp_v14 (x + y))
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try simp [semilen_append, BSeq.semilen_cons]
    try omega

def S_comp_v14 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => R_comp_v14 x ∪ S_comp_v14 (x + y)
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try simp [semilen_append, BSeq.semilen_cons]
    try omega

def check_lemma7_v14 (x : BSeq) : Bool :=
  (S_comp_v14 x).card ≤ BSeq.semilen x * treeLeavesOfSeq x + 1

#eval! check_lemma7_v14 BSeq.nil
#eval! check_lemma7_v14 (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_lemma7_v14 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_lemma7_v14 (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_lemma7_v14 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def R_comp_v18 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => insert (BSeq.cons x y) (R_comp_v18 (x + y))
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try rw [semilen_append]
    try rw [BSeq.semilen_cons]
    try omega

def S_comp_v18 : BSeq → Finset BSeq
  | BSeq.nil => {BSeq.nil}
  | BSeq.cons x y => R_comp_v18 x ∪ S_comp_v18 (x + y)
termination_by x => BSeq.semilen x
decreasing_by
  all_goals
    simp_wf
    try rw [semilen_append]
    try rw [BSeq.semilen_cons]
    try omega

def check_lemma7_v18 (x : BSeq) : Bool :=
  (S_comp_v18 x).card ≤ BSeq.semilen x * treeLeavesOfSeq x + 1

#eval! check_lemma7_v18 BSeq.nil
#eval! check_lemma7_v18 (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_lemma7_v18 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_lemma7_v18 (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_lemma7_v18 (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def check_inter_lemma (x : BSeq) : Bool :=
  BSeq.semilen x + 1 ≤ treeLeavesOfSeq x + (R_comp_v18 x ∩ S_comp_v18 x).card

#eval! check_inter_lemma BSeq.nil
#eval! check_inter_lemma (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_inter_lemma (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_inter_lemma (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_inter_lemma (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def check_R_diff_S (x : BSeq) : Bool :=
  (R_comp_v18 x \ S_comp_v18 x).card ≤ treeLeavesOfSeq x

#eval! check_R_diff_S BSeq.nil
#eval! check_R_diff_S (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_R_diff_S (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_R_diff_S (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_R_diff_S (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

theorem inter_cons_nil_eq_R [LozanoContextFull] (u : BSeq) :
    R (BSeq.cons u BSeq.nil) ∩ S (BSeq.cons u BSeq.nil) = R u := by
      -- By definition of $R$ and $S$, we know that $R (u.cons BSeq.nil) = insert (u.cons BSeq.nil) (R u)$ and $S (u.cons BSeq.nil) = R u ∪ S (u.cons BSeq.nil)$.
      have hR : (‹LozanoContextFull›.R (u.cons BSeq.nil)) = insert (u.cons BSeq.nil) (‹LozanoContextFull›.R u) := by
        convert ( ‹LozanoContextFull›.R_cons u BSeq.nil ) using 1;
        -- By definition of $+$, we have $u + BSeq.nil = u$.
        have h_append_nil : u + BSeq.nil = u := by
          -- By definition of append, we know that u + BSeq.nil = u for any BSeq u.
          induction' u with u ih;
          · rfl;
          · -- By definition of append, we know that u.cons ih + BSeq.nil = u.cons (ih + BSeq.nil).
            have h_append_cons : u.cons ih + BSeq.nil = u.cons (ih + BSeq.nil) := by
              exact?;
            aesop
        rw [h_append_nil]
      have hS : (‹LozanoContextFull›.S (u.cons BSeq.nil)) = (‹LozanoContextFull›.R u) ∪ (‹LozanoContextFull›.S (u.cons BSeq.nil)) := by
        -- By definition of $S$, we know that $S (u.cons BSeq.nil) = R u ∪ S (u.cons BSeq.nil)$.
        apply Eq.symm; exact (by
          have := ‹LozanoContextFull›.S_cons_def u BSeq.nil;
          aesop ( simp_config := { singlePass := true } ) ;)
      simp_all +decide [ Finset.ext_iff ];
      -- If $a$ is in $R(u + \text{nil})$ and $S(u + \text{nil})$, then by $hR$, $a$ must be either $u + \text{nil}$ or in $R(u)$. But if $a$ is $u + \text{nil}$, then by $hS$, $a$ would also be in $S(u + \text{nil})$, which is true. However, if $a$ is in $R(u)$, then by $hS$, $a$ is in $S(u + \text{nil})$, which is also true. So the forward direction holds.
      intros a
      constructor
      intro h
      obtain ⟨haR, haS⟩ := h
      have haR' : a = u.cons BSeq.nil ∨ a ∈ ‹LozanoContextFull›.R u := by
        exact haR
      have haS' : a ∈ ‹LozanoContextFull›.S (u.cons BSeq.nil) := by
        assumption
      have haR'' : a ∈ ‹LozanoContextFull›.R u := by
        cases haR' <;> simp_all +decide [ Finset.ext_iff ];
        -- Since $u.cons BSeq.nil \in S (u.cons BSeq.nil)$ and $S (u.cons BSeq.nil) = R u \cup S (u.cons BSeq.nil)$, it follows that $u.cons BSeq.nil \in R u$.
        have h_contra : u.cons BSeq.nil ∈ (‹LozanoContextFull›.R u) ∪ (‹LozanoContextFull›.S (u.cons BSeq.nil)) := by
          exact Finset.mem_union_right _ haS
          skip
        generalize_proofs at *; (
        simp +zetaDelta at *; (
        -- Since $u.cons BSeq.nil$ is in $S (u.cons BSeq.nil)$ and $S (u.cons BSeq.nil)$ is a subset of $R u ∪ S (u.cons BSeq.nil)$, it follows that $u.cons BSeq.nil$ must be in $R u$.
        apply Or.resolve_right h_contra; exact (by
        intro h; have := @S_mem_semilen_lt; simp_all +decide ;
        -- Apply the hypothesis `this` to `u.cons BSeq.nil` and derive the contradiction.
        have := @this (‹LozanoContextFull›) (u.cons BSeq.nil) (by
        exact ne_of_apply_ne ( fun x => x ) ( by simp +decide )) (u.cons BSeq.nil) h; simp_all +decide [ BSeq.semilen_cons ] ;)
        skip))
      exact haR'';
      exact fun ha => ⟨ Or.inr ha, hS a ha ⟩

def isLinear : BSeq → Bool
  | BSeq.nil => true
  | BSeq.cons u v => match v with
    | BSeq.nil => isLinear u
    | _ => false

def check_semilen_lt_treeLeaves (x : BSeq) : Bool :=
  if isLinear x then true else BSeq.semilen x < treeLeavesOfSeq x

def check_semilen_le_S_card (x : BSeq) : Bool :=
  if isLinear x then BSeq.semilen x ≤ (S_comp_v18 x).card else true

#eval! check_semilen_lt_treeLeaves BSeq.nil
#eval! check_semilen_lt_treeLeaves (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_semilen_lt_treeLeaves (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_semilen_lt_treeLeaves (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_semilen_lt_treeLeaves (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

#eval! check_semilen_le_S_card BSeq.nil
#eval! check_semilen_le_S_card (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_semilen_le_S_card (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_semilen_le_S_card (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))

def slack (x : BSeq) : Nat :=
  if isLinear x then 0 else BSeq.semilen x - 2

theorem lemma7_strong_algebra_nonlinear [LozanoContext] (u v : BSeq) (hu : ¬isLinear u) :
    2 * BSeq.semilen u + BSeq.semilen v + 1 - slack u - slack v ≤
    BSeq.semilen u * treeLeavesOfSeq v + BSeq.semilen v * treeLeavesOfSeq u + treeLeavesOfSeq u + treeLeavesOfSeq v := by
      have h_slack_bounds : 1 ≤ BSeq.semilen u ∧ 2 ≤ treeLeavesOfSeq u ∧ 0 ≤ BSeq.semilen v ∧ 1 ≤ treeLeavesOfSeq v := by
        have h_subst : ∀ x : BSeq, ¬isLinear x → 1 ≤ BSeq.semilen x ∧ 2 ≤ treeLeavesOfSeq x := by
          intro x hx
          induction' x with x ih;
          · contradiction;
          · cases ih <;> cases x <;> simp_all! +arith +decide;
            · rename_i k hk;
              cases k <;> simp_all +arith +decide;
              · exact?;
              · exact?;
            · rename_i k hk₁ hk₂;
              rename_i a b;
              cases a <;> cases k <;> simp_all +arith +decide;
              · rename_i a;
                linarith [ show 1 ≤ treeLeavesOfSeq a from by exact? , show 1 ≤ treeLeavesOfSeq b from by exact? ];
              · linarith;
              · linarith [ show 0 ≤ treeLeavesOfSeq b from Nat.zero_le _ ];
              · grind;
        exact ⟨ h_subst u hu |>.1, h_subst u hu |>.2, Nat.zero_le _, by exact? ⟩;
      unfold slack;
      rcases k : treeLeavesOfSeq u with ( _ | _ | k ) <;> rcases l : treeLeavesOfSeq v with ( _ | _ | l ) <;> simp_all +arith +decide;
      · grind;
      · grind

/-
Search for a counterexample to Lemma 7 up to semilength 8 using iterative generation to avoid recursion issues.
-/
def generateBSeqs (maxN : Nat) : Array (List BSeq) := Id.run do
  let mut arr : Array (List BSeq) := Array.mkArray (maxN + 1) []
  arr := arr.set! 0 [BSeq.nil]
  for n in [1:maxN+1] do
    let mut seqs : List BSeq := []
    -- We want semilen = n.
    -- cons x y has semilen = semilen x + semilen y + 1.
    -- Let k = semilen x. Then semilen y = n - 1 - k.
    -- k ranges from 0 to n - 1.
    for k in [0:n] do
      let lefts := arr.get! k
      let rights := arr.get! (n - 1 - k)
      for x in lefts do
        for y in rights do
          seqs := (BSeq.cons x y) :: seqs
    arr := arr.set! n seqs
  return arr

def check_inequality (x : BSeq) : Bool :=
  (S_comp_v18 x).card ≤ BSeq.semilen x * treeLeavesOfSeq x + 1

def check_slack_additive (x : BSeq) : Bool :=
  (S_comp_v18 x).card ≤ BSeq.semilen x * treeLeavesOfSeq x + BSeq.semilen x + 1

def check_slack_factor (x : BSeq) : Bool :=
  (S_comp_v18 x).card ≤ BSeq.semilen x * (treeLeavesOfSeq x + 1) + 1

def findCounterexample (maxN : Nat) : String := Id.run do
  let allSeqs := generateBSeqs maxN
  for n in [0:maxN+1] do
    for x in allSeqs.get! n do
      if ¬ check_inequality x then
        let s_card := (S_comp_v18 x).card
        let rhs := BSeq.semilen x * treeLeavesOfSeq x + 1
        let slack_add := check_slack_additive x
        let slack_fac := check_slack_factor x
        return s!"Counterexample found at n={n}: {repr x} | S_card={s_card} | RHS={rhs} | SlackAdd={slack_add} | SlackFac={slack_fac}"
  return "No counterexample found"

#eval! findCounterexample 8

/-
Check the intersection lemma and a stronger version.
-/
#eval! check_inter_lemma BSeq.nil
#eval! check_inter_lemma (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_inter_lemma (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_inter_lemma (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_inter_lemma (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def check_inter_lemma_strong (x : BSeq) : Bool :=
  BSeq.semilen x + 2 ≤ treeLeavesOfSeq x + (R_comp_v18 x ∩ S_comp_v18 x).card

#eval! check_inter_lemma_strong BSeq.nil
#eval! check_inter_lemma_strong (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_inter_lemma_strong (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_inter_lemma_strong (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_inter_lemma_strong (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

/-
Check if the stronger bound `(S x).card ≤ semilen x + 1` holds.
-/
def check_stronger_bound (x : BSeq) : Bool :=
  (S_comp_v18 x).card ≤ BSeq.semilen x + 1

#eval! check_stronger_bound BSeq.nil
#eval! check_stronger_bound (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_stronger_bound (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_stronger_bound (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_stronger_bound (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def findCounterexampleStronger (maxN : Nat) : String := Id.run do
  let allSeqs := generateBSeqs maxN
  for n in [0:maxN+1] do
    for x in allSeqs.get! n do
      if ¬ check_stronger_bound x then
        let s_card := (S_comp_v18 x).card
        let rhs := BSeq.semilen x + 1
        return s!"Counterexample found at n={n}: {repr x} | S_card={s_card} | RHS={rhs}"
  return "No counterexample found"

#eval! findCounterexampleStronger 8

/-
Check if S x is always a subset of R x.
-/
def check_S_subset_R (x : BSeq) : Bool :=
  S_comp_v18 x ⊆ R_comp_v18 x

#eval! check_S_subset_R BSeq.nil
#eval! check_S_subset_R (BSeq.cons BSeq.nil BSeq.nil)
#eval! check_S_subset_R (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) BSeq.nil)
#eval! check_S_subset_R (BSeq.cons BSeq.nil (BSeq.cons BSeq.nil BSeq.nil))
#eval! check_S_subset_R (BSeq.cons (BSeq.cons BSeq.nil BSeq.nil) (BSeq.cons BSeq.nil BSeq.nil))

def findCounterexampleSubset (maxN : Nat) : String := Id.run do
  let allSeqs := generateBSeqs maxN
  for n in [0:maxN+1] do
    for x in allSeqs.get! n do
      if ¬ check_S_subset_R x then
        return s!"Counterexample to S ⊆ R found at n={n}: {repr x}"
  return "No counterexample found"

#eval! findCounterexampleSubset 8

/-
Helper lemma: If treeLeaves x = 1, then S x ⊆ R x.
-/
theorem lemma_subset_R [LozanoContextFull] (x : BSeq) (h : treeLeavesOfSeq x = 1) :
    S x ⊆ R x := by
      have := @S_subset_R_of_treeLeaves_eq_one;
      contrapose! this;
      refine' ⟨ _, x, h, this ⟩

/-
Prove `treeLeaves_add_of_ne_nil` using `forestLeaves_add`.
-/
theorem treeLeaves_add_of_ne_nil (x y : BSeq) (hx : x ≠ BSeq.nil) :
    treeLeavesOfSeq (x + y) = treeLeavesOfSeq x + forestLeavesOfSeq y := by
      convert treeLeaves_eq_forestLeaves_of_ne_nil _ _ using 1;
      · convert treeLeaves_cons x y using 1;
        rw [ forestLeaves_add, treeLeaves_eq_forestLeaves_of_ne_nil x hx ];
      · cases x <;> cases y <;> tauto

/-
Prove that `nil` is always in `R x` and `S x`.
-/
theorem nil_mem_R [LozanoContextFull] (x : BSeq) : BSeq.nil ∈ R x := by
  -- By induction on the semilen of x, we can show that BSeq.nil is in R x for any x.
  induction' k : BSeq.semilen x using Nat.strong_induction_on with k ih generalizing x;
  cases x;
  · exact ‹LozanoContextFull›.R_nil.symm ▸ Finset.mem_singleton_self _;
  · rename_i x y;
    rename_i h;
    rename_i h';
    rw [ h'.R_cons ];
    simp +zetaDelta at *;
    convert ih _ _ _ rfl;
    rw [ ← k ];
    rw [ semilen_append ] ; norm_num

theorem nil_mem_S [LozanoContextFull] (x : BSeq) : BSeq.nil ∈ S x := by
  -- By induction on the semilen of x, we can show that BSeq.nil is in S x for any x.
  induction' k : BSeq.semilen x using Nat.strong_induction_on with k ih generalizing x;
  cases' x with x y;
  · exact ‹LozanoContextFull›.S_nil.symm ▸ Finset.mem_singleton_self _;
  · -- By definition of $S$, we know that $BSeq.nil \in S (x + y)$.
    have h_nil_in_S_xy : BSeq.nil ∈ (‹LozanoContextFull›.S (x + y)) := by
      apply ih (BSeq.semilen (x + y));
      · rw [ ← k ];
        rw [ BSeq.semilen_cons, semilen_append ] ; simp +arith +decide;
      · rfl;
    have := ‹LozanoContextFull›.S_cons_def x y; aesop;

/-
Prove `S (cons a b) = R a ∪ S b` when `a` is linear.
-/
theorem lemma_S_cons_linear_of_treeLeaves_eq_one [LozanoContextFull] (a b : BSeq) (ha : treeLeavesOfSeq a = 1) :
    S (BSeq.cons a b) = R a ∪ S b := by
      induction' a with u v hu hv generalizing b;
      · rename_i h;
        convert h.S_cons_def BSeq.nil b using 1;
      · by_cases h : v = BSeq.nil <;> simp_all +decide [ treeLeaves_cons ];
        · -- By the induction hypothesis, we know that S (cons u nil) = R u ∪ S nil.
          have h_ind : ‹LozanoContextFull›.S (BSeq.cons u BSeq.nil) = ‹LozanoContextFull›.R u ∪ ‹LozanoContextFull›.S BSeq.nil := by
            exact hu _;
          convert congr_arg ( fun s => ‹LozanoContextFull›.R ( BSeq.cons u BSeq.nil ) ∪ s ) ( hu b ) using 1;
          · convert ‹LozanoContextFull›.S_cons_def ( BSeq.cons u BSeq.nil ) b using 1;
          · ext x; by_cases hx : x ∈ ‹LozanoContextFull›.R u <;> simp +decide [ hx ] ;
            have := ‹LozanoContextFull›.R_cons u BSeq.nil; simp_all +decide [ Finset.ext_iff ] ;
            rw [ show u + BSeq.nil = u from by
                  -- By definition of append, we have u + BSeq.nil = u.
                  have h_append_nil : ∀ u : BSeq, u + BSeq.nil = u := by
                    intro u; exact (by
                    induction' u with u v hu hv generalizing b;
                    · rfl;
                    · exact congr_arg ( fun x => BSeq.cons u x ) ( hv v ));
                  exact h_append_nil u ] ; aesop;
        · contrapose! ha;
          exact ne_of_gt ( lt_add_of_pos_of_le ( Nat.pos_of_ne_zero ( by
            exact ne_of_gt ( ‹LozanoContextFull›.treeLeaves_pos u ) ) ) ( Nat.one_le_iff_ne_zero.mpr ( by
            exact ne_of_gt ( by linarith [ treeLeaves_eq_forestLeaves_of_ne_nil v h, ‹LozanoContextFull›.treeLeaves_pos v ] ) ) ) )

/-
Decomposition lemma for S(cons (cons a b) nil).
-/
theorem lemma_S_cons_nil_decomp [LozanoContextFull] (a b : BSeq) :
    S (BSeq.cons (BSeq.cons a b) BSeq.nil) = insert (BSeq.cons a b) (R a ∪ S (BSeq.cons (a + b) BSeq.nil)) := by
      convert Set.ext _;
      rotate_left;
      exact BSeq;
      exact { x | x ∈ ( ‹LozanoContextFull›.R ( a.cons b ) ∪ ‹LozanoContextFull›.S ( ( a.cons b ) + BSeq.nil ) ) };
      exact { x | x ∈ ‹LozanoContextFull›.R a ∪ ‹LozanoContextFull›.S ( ( a + b ).cons BSeq.nil ) ∪ { a.cons b } };
      · have := ‹LozanoContextFull›.R_cons a b; have := ‹LozanoContextFull›.S_cons_def a b; simp_all +decide [ Set.ext_iff ] ;
        have := ‹LozanoContextFull›.R_cons ( a + b ) BSeq.nil; have := ‹LozanoContextFull›.S_cons_def ( a + b ) BSeq.nil; simp_all +decide [ Set.ext_iff ] ;
        simp_all +decide [ show a.cons b + BSeq.nil = a.cons b from by
                            -- By definition of addition for BSeq, adding nil to any sequence results in the sequence itself.
                            have h_add_nil : ∀ x : BSeq, x + BSeq.nil = x := by
                              intro x; exact (by
                              induction' x with x y ihx ihy;
                              · rfl;
                              · -- By definition of BSeq.append, we have BSeq.cons x y + BSeq.nil = BSeq.cons x (y + BSeq.nil).
                                have h_append_cons : BSeq.cons x y + BSeq.nil = BSeq.cons x (y + BSeq.nil) := by
                                  exact?;
                                rw [h_append_cons, ihy]);
                            exact h_add_nil _ ];
        rw [ show a + b + BSeq.nil = a + b from by
              -- By definition of BSeq.append, appending BSeq.nil to any sequence x results in x itself.
              have h_append_nil : ∀ x : BSeq, x + BSeq.nil = x := by
                intro x; exact (by
                induction' x with x y ihx ihy;
                · rfl;
                · -- By definition of BSeq.append, we have BSeq.cons x y + BSeq.nil = BSeq.cons x (y + BSeq.nil).
                  have h_append_cons : BSeq.cons x y + BSeq.nil = BSeq.cons x (y + BSeq.nil) := by
                    exact?;
                  rw [h_append_cons, ihy]);
              exact h_append_nil _ ] ; aesop;
      · simp +decide [ Set.ext_iff, Finset.ext_iff ];
        exact ⟨ fun h => by have := ‹LozanoContextFull›.S_cons_def ( a.cons b ) BSeq.nil; aesop, fun h => by have := ‹LozanoContextFull›.S_cons_def ( a.cons b ) BSeq.nil; aesop ⟩

/-
Prove `x + nil = x` for BSeq.
-/
theorem add_nil (x : BSeq) : x + BSeq.nil = x := by
  -- We'll use induction on x to prove that x + BSeq.nil = x.
  induction' x with x ih;
  · rfl;
  · -- By definition of addition for BSeq, we have x.cons ih + BSeq.nil = x.cons (ih + BSeq.nil).
    have h_add : x.cons ih + BSeq.nil = x.cons (ih + BSeq.nil) := by
      exact?;
    aesop

/-
Prove `S (cons x nil) = R x ∪ S x`.
-/
theorem S_cons_nil_eq [LozanoContextFull] (x : BSeq) :
    S (BSeq.cons x BSeq.nil) = R x ∪ S x := by
  simp [S_cons_def, add_nil]
